{"name": "test_make_wrong_add_money_parameter", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 9 == 10", "trace": "@pytest.mark.xfail\n    def test_make_wrong_add_money_parameter():\n        \"\"\"\n        Payment with negative amount\n        \"\"\"\n        test_wallet = Wallet(10)\n        test_wallet.add_money(-1)\n>       assert test_wallet.balance() == 10\nE       assert 9 == 10\n\ntest_simple.py:130: AssertionError"}, "description": "\n    Payment with negative amount\n    ", "start": 1607421553682, "stop": 1607421553682, "uuid": "757156e6-fcd8-4e56-b7ab-088e7f9b999f", "historyId": "265b8d5fd1b741f1a4534c2427b8ecaf", "testCaseId": "8ad1ee1c0e658b825fcb15a7f624a94e", "fullName": "tests.test_simple#test_make_wrong_add_money_parameter", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_simple"}, {"name": "host", "value": "scc-107-05"}, {"name": "thread", "value": "28200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_simple"}]}